### ISSUE TITLE
While transposing the chart key doesn't change

### ISSUE THREAD

**Issue by Natim** [open-chords-charts/chart-editor#2]
During the elm-europe demo I realised the key of the chord stay the previous note rather than the transposed one.

**Comment by cbenz** [comment]
Hi @Natim! You're right, I noticed the bug the day before the talk. I should fix it soon.

**Comment by cbenz** [comment]
This issue is now fixed, thanks for reporting :-)

![image](https://user-images.githubusercontent.com/12686/27076223-e0b14018-502c-11e7-844b-10ecae0bbe3d.png)
